/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import Exercice1.Somme;
import Exercice2.Paire;

import java.util.function.Predicate;

public class App {



    public static void question1_1(){
        Somme <Integer> somme1 = new Somme<Integer>() {
            @Override
            public Integer somme(Integer var1, Integer var2) {
                return var1+var2;
            }
        };

        Somme <String> somme2 = new Somme<String>() {
            @Override
            public String somme(String var1, String var2) {
                return var1+var2;
            }
        };

        Somme <Double> somme3 = new Somme<Double>() {
            @Override
            public Double somme(Double var1, Double var2) {
                return var1+var2;
            }
        };


        Somme<Long> somme4 = new Somme<Long>() {
            @Override
            public Long somme(Long var1, Long var2) {
                return var1+var2;
            }
        };
    }



    public static void exo2_question1(){

        Paire<Integer,Integer> bob = new Paire<>(80,120);
        Paire<Integer,Integer> Cla = new Paire<>(101,120);
        Paire<Integer,Integer> lea = new Paire<>(201,120);

        Paire<Integer,Double> micheal = new Paire<>(150,220.0);


        Predicate<Paire<Integer,Integer>> troppetit = p -> p.fst<100;
        troppetit.test(bob);
        troppetit.test(Cla);


        Predicate<Paire<Integer,Integer>> tropgrande = p -> p.fst>200;

        tropgrande.test(bob);
        tropgrande.test(lea);

        Predicate<Paire<Integer,Double>> troplourd = p -> p.snd>150.0;
        troplourd.test(micheal);


        Predicate <Boolean> tailleincorrect = (p ) -> {
             Boolean rtr=false;
            tropgrande.and(tropgrande);


            return rtr;
        };



        Predicate<Boolean> poidsCorrect = (p) -> {
            Boolean rtr=true;

            troppetit.and(tropgrande);



            return  rtr;
        };

        Predicate<Boolean> accesAutorise = (p) -> {
            Boolean rtr=false;

            tailleincorrect.and(poidsCorrect);



            return  rtr;
        };


    }


    public static void main(String[] args) {
        question1_1();
        exo2_question1();
        System.out.println();
    }
}
