/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import Exercice1.Somme;

public class App {



    public static void question1_1(){
        Somme <Integer> somme1 = new Somme<Integer>() {
            @Override
            public Integer somme(Integer var1, Integer var2) {
                return var1+var2;
            }
        };

        Somme <String> somme2 = new Somme<String>() {
            @Override
            public String somme(String var1, String var2) {
                return var1+var2;
            }
        };

        Somme <Double> somme3 = new Somme<Double>() {
            @Override
            public Double somme(Double var1, Double var2) {
                return var1+var2;
            }
        };


        Somme<Long> somme4 = new Somme<Long>() {
            @Override
            public Long somme(Long var1, Long var2) {
                return var1+var2;
            }
        }
    }




    public static void main(String[] args) {
        System.out.println();
    }
}
